theme: osuny
_merge: deep
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: true
  posts:
    index:
      layout: grid
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo-blanc.svg'